### PR TITLE
directory readmes as project documentation

### PR DESCRIPTION
**Pull request by nathangibson**
@robcast @sinairusinek Interested in your thoughts about doing things this way

### CODE REVIEW

**Comment by nathangibson** [comment]
See especially https://github.com/Hist-ME/URIs/tree/directory-documentation/persons/aligned-uris/usaybia.net as an example and notice how the README displays nicely inline underneath the files.

**Review by robcast — APPROVED** [review]
I like it. I would add information for the ismi data in a README afterwards.

**Comment by sinairusinek** [comment]
Yes - but what happens when there are two data sets in a directory? do we have one common readme for the entire directory, open a separate directory, or create multiple readmes?

**Comment by nathangibson** [comment]
@sinairusinek 

> Yes - but what happens when there are two data sets in a directory? do we have one common readme for the entire directory, open a separate directory, or create multiple readmes?

So sorry, I'm still catching up on stuff. 

The idea is to create a separate directory for project-submitted files so that each project can have its own readme. We can still create a combined list though as needed. 

I'll do a pull request here to show you what I mean.

**Comment by nathangibson** [comment]
OK I resolved some file conflicts and made sure I have everything up-to-date. (Except I kept the non-aligned dijest persons. @sinairusinek if you intentionally deleted that you can re-delete it.)

@sinairusinek I suggest taking a look at this branch (https://github.com/Hist-ME/URIs/tree/directory-documentation) and seeing if you have any objections to the directory structure.

**Pull request merged**
