### PR TITLE
Guidance for non-aligned URIs, places example

### PR DESCRIPTION
**Pull request by nathangibson**
@robcast What do you think?

### CODE REVIEW

**Comment by robcast** [comment]
Looks good to me!

Should we add information about related standards like the LinkedPlaces LP-TSV format for places in the places subfolder?

**Comment by nathangibson** [comment]
@robcast Yes, good idea, I've assigned you #4 if you're up for it :-)

**Comment by sinairusinek** [comment]
Just a thought: wouldn't it be better to simply work with the WHG? I've been meaning to align Kima with it anyway. The only problem I have is with the 'start' field in the LP-TSV.

**Comment by robcast** [comment]
Yes, http://whgazetteer.org/ was what I had in mind. It required the `date` column when I tried it last (I used 0 or 700 for all as I don't have enough date attestations).

Maybe we can talk to Karl to make the column optional ;-)

**Comment by nathangibson** [comment]
@sinairusinek Clarification: Do you think that for places, WHG could entirely replace the need to upload spreadsheets here? I.e. that the entry barrier is low enough for small/limited-tech projects and that all of the reconciliation with each other's projects can be done satisfactorily there? 

I haven't yet tried uploading usaybia.net place records to it, but I want to soon!

**Comment by sinairusinek** [comment]
@nathangibson can't say, because I haven't tried it either... but I plan to.  It would be good to have the spreadsheets here to save the alignments between the ME relevant entities,  but in order to do the alignment I am eager to see Karl's solution as well as the others that are offered on cluster 1.

**Comment by robcast** [comment]
I don't think we should replace this with WHG. 

I would suggest to upload your places to WHG and then download the enriched list with WHG alignment and post it here.

Hmm, would that then go in the "aligned" folder?

**Comment by sinairusinek** [comment]
agreed!

**Comment by nathangibson** [comment]
Sounds good! 

Yep, that would then go in the aligned-uris folder.

I just tried uploading a couple of records to WHG and it was easier than I thought. However a potential problem at this stage is that I don't see any way to reconcile with datasets other than Getty TGN and Wikidata. If neither of those have the place you're looking for, then it's not a comprehensive solution for aligning links between other projects.

**Comment by nathangibson** [comment]
By the way I noticed in https://github.com/LinkedPasts/linked-places/blob/master/tsv_0.2.md regarding start date: 
> A start value alone typically indicates the publication date of the title_source.

This needs some clarification but it sounds as if it is really a kind of "attested" date for the name, which would be more usable than having to assert when a place originated.

**Comment by robcast** [comment]
Yes, my understanding about the format is also that it is considering your data as attestation to the place name so the date is about your attestation.

Still, in our data we don't have meaningful attestation dates for most places and I would be happy not to have to provide a date.

**Comment by sinairusinek** [comment]
so I delved deeper into it and it looks like the LP-1 format Json might actually be more lenient:  the 'when' is not required. There, what is required is 'citation'(= source) to at least one attested variant of the place name. This is easier for me to provide, depending on how historical a source is expected to be (if a library catalogue can be a source, I'm covered).

**Pull request merged**
